// Stage 4A3: Lifecycle tests — 48 tests, deterministic clock.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { PaperRuntimeSupervisor } from '../../src/paper/PaperRuntimeSupervisor';
import { PaperRuntimeRegistry, type PaperRuntimeBinding } from '../../src/paper/PaperRuntimeRegistry';
import { PaperFastPathCoordinator } from '../../src/paper/PaperFastPathCoordinator';
import { PaperExecutionService } from '../../src/paper/PaperExecutionService';
import { PaperLedgerStore } from '../../src/paper/PaperLedgerStore';
import { FastPipeline } from '../../src/pipeline/FastPipeline';
import { KillSwitch } from '../../src/router/KillSwitch';
import { createMarketSnapshotStore } from '../../src/data/MarketSnapshotStore';
import { createCandleSeriesStore } from '../../src/data/CandleSeriesStore';
import { InMemoryPaperRuntimeEventSink } from '../../src/paper/PaperObservability';
import { PaperRuntimeLifecycleError, type PaperRuntimeLifecycleAdapter } from '../../src/paper/PaperLifecycle';
import type { ExchangeId } from '../../src/data/MarketIdentity';
import type { PaperAccountConfig } from '../../src/types/paper-account';

const EXCH_BG: ExchangeId = 'bitget';
const EXCH_BN: ExchangeId = 'binance';
const FUTURE = Date.now() + 120_000;
let clockMs = FUTURE;
function dClock() { return { now: () => clockMs }; }
function advance(ms: number) { clockMs += ms; }

function mkTicker(ex: ExchangeId, sym: string, last: number, ts: number) { return { exchange: ex, instId: sym, channel: 'ticker' as const, last, bestBid: last-1, bestAsk: last+1, volume24h: 1000, high24h: last*1.02, low24h: last*0.98, ts }; }
function mkKline(ex: ExchangeId, sym: string, close: number, ts: number) { return { exchange: ex, instId: sym, channel: 'kline' as const, interval: '1m', open: close*0.999, high: close*1.001, low: close*0.998, close, volume: 100, ts, confirm: true }; }
function momentumResult() { return { name: 'CompositeMomentum' as const, composite_score: 85, regime_state: 'STRONG_BULLISH' as const, in_cooldown: false, dimension_scores: { hull_big_trend: { value:1,weight:1 }, stc_momentum: { value:1,weight:1 }, volume_micro: { value:1,weight:1 } }, lag_bars: 0, elapsedMs: 0 }; }

class TrackingAdapter implements PaperRuntimeLifecycleAdapter { startCalls=0; stopCalls=0; startFail=false; stopFail=false; start(){this.startCalls++; if(this.startFail)throw new Error('adapter start fail');} stop(){this.stopCalls++; if(this.stopFail)throw new Error('adapter stop fail');} }

async function makeBinding(aid: string, ex: ExchangeId, cash: number, sym: string, dir: 'long'|'short') {
  const d = await fs.mkdtemp(path.join(os.tmpdir(), 's4a3-'));
  const s = createMarketSnapshotStore({ staleAfterMs: 60_000 });
  s.updateTicker({ ticker: mkTicker(ex, sym, 50000, FUTURE), receivedAt: FUTURE });
  const c = createCandleSeriesStore({ capacityPerSeries: 500 });
  for (let i = 0; i < 200; i++) { const k = mkKline(ex, sym, 49000+i*10, FUTURE-(200-i)*60_000); s.updateClosedKline({ kline: k, receivedAt: k.ts }); c.appendClosedKline({ kline: k, receivedAt: k.ts }); }
  const ac: PaperAccountConfig = { accountId: aid, exchange: ex, initialCashUsd: cash };
  const ks = new KillSwitch(ex, { totalCapitalUsd: cash, maxPositionPct: 1, maxSinglePositionPct: 1, allowConcentration: true });
  const fp = new FastPipeline({ exchange: ex, router: { exchange: ex, getBiasReport: () => ({ exchange: ex, updatedAt: FUTURE, assets: [{ symbol: sym, direction: dir, confidence: 85, suggestedPositionPct: 0.1 }], whitelist: [sym] }), getConfig: () => ({ maxBiasReportAgeHours: 999 }), killSwitch: ks }, indicatorService: { calculateAll: async () => [momentumResult()] }, marketData: { exchange: ex, snapshotStore: s, candleStore: c, interval: '1m', minimumSeries: 100, seriesLimit: 200 } });
  const svc = await PaperExecutionService.open(ac, new PaperLedgerStore(ac, { baseDir: d }));
  return { binding: { accountId: aid, exchange: ex, pipeline: fp, service: svc, coordinator: new PaperFastPathCoordinator(fp, svc, ex) }, dir: d };
}

function sup(eventSink?: InMemoryPaperRuntimeEventSink) { return new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry(), eventSink, clock: dClock() }); }
const SIG = { exchange: EXCH_BG, symbol: 'BTCUSDT', source: 's' };
const P = { feeBps: 10, slippageBps: 5 };

// 1–7 Initial
test('1. register → stopped', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'stopped'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('2. init acceptingRuns=false', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); assert.equal(s.lifecycle('a1', EXCH_BG).acceptingRuns, false); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('3. init inFlight=0', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); assert.equal(s.lifecycle('a1', EXCH_BG).inFlightRuns, 0); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('4. snapshot frozen', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); assert.ok(Object.isFrozen(s.lifecycle('a1', EXCH_BG))); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('5. lifecycleAll deterministic', async () => { const b1 = await makeBinding('b', EXCH_BG, 100_000, 'BTCUSDT', 'long'); const b2 = await makeBinding('a', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b2.binding); s.register(b1.binding); const all = s.lifecycleAll(); assert.equal(all.length, 2); assert.equal(all[0].accountId, 'a'); } finally { await fs.rm(b1.dir, { recursive: true, force: true }); await fs.rm(b2.dir, { recursive: true, force: true }); } });
test('6. lifecycleAll defensive', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); assert.notStrictEqual(s.lifecycleAll(), s.lifecycleAll()); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('7. not registered throws', () => { assert.throws(() => sup().lifecycle('no', EXCH_BG), PaperRuntimeLifecycleError); });

// 8–16 Start
test('8. start → running', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'running'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('9. start increments gen', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).generation, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('10. running accepts run', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); const r = await s.run('a1', SIG, P); assert.equal(r.paperEvent!.status, 'applied'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('11. stopped rejects run', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await assert.rejects(() => s.run('a1', SIG, P), PaperRuntimeLifecycleError); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('12. start adapter fail → failed', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); ad.startFail = true; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await assert.rejects(() => s.start('a1', EXCH_BG)); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'failed'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('13. failed start gen unchanged', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); ad.startFail = true; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); try { await s.start('a1', EXCH_BG); } catch {} assert.equal(s.lifecycle('a1', EXCH_BG).generation, 0); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('14. start while running idempotent', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await s.start('a1', EXCH_BG); await s.start('a1', EXCH_BG); assert.equal(ad.startCalls, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('15. concurrent start → adapter once', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await Promise.all([s.start('a1', EXCH_BG), s.start('a1', EXCH_BG)]); assert.equal(ad.startCalls, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('16. failed rejects run', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); ad.startFail = true; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); try { await s.start('a1', EXCH_BG); } catch {} await assert.rejects(() => s.run('a1', SIG, P), PaperRuntimeLifecycleError); } finally { await fs.rm(d, { recursive: true, force: true }); } });

// 17–25 Stop
test('17. stop → stopped', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.stop('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'stopped'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('18. stopped rejects run', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.stop('a1', EXCH_BG); await assert.rejects(() => s.run('a1', SIG, P), PaperRuntimeLifecycleError); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('19. stop calls adapter', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await s.start('a1', EXCH_BG); await s.stop('a1', EXCH_BG); assert.equal(ad.stopCalls, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('20. stop adapter fail → failed, ledger ok', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); ad.stopFail = true; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await s.start('a1', EXCH_BG); await s.run('a1', SIG, P); await s.stop('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'failed'); assert.equal(b.service.snapshot().processedFills, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('21. concurrent stop → adapter once', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await s.start('a1', EXCH_BG); await Promise.all([s.stop('a1', EXCH_BG), s.stop('a1', EXCH_BG)]); assert.equal(ad.stopCalls, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('22. stop waits for in-flight', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); const runP = s.run('a1', SIG, P); const stopP = s.stop('a1', EXCH_BG); const [r] = await Promise.all([runP, stopP]); assert.equal(r.paperEvent!.status, 'applied'); assert.equal(s.lifecycle('a1', EXCH_BG).inFlightRuns, 0); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('23. coordinator exception → inFlight decremented', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); const orig = b.pipeline.execute.bind(b.pipeline); b.pipeline.execute = async () => { throw new Error('boom'); }; try { await s.run('a1', SIG, P); } catch {} assert.equal(s.lifecycle('a1', EXCH_BG).inFlightRuns, 0); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('24. inFlight never negative', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); for (let i = 0; i < 3; i++) { try { await s.run('a1', SIG, P); } catch {} } assert.ok(s.lifecycle('a1', EXCH_BG).inFlightRuns >= 0); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('25. pipeline exact-once', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { let calls = 0; const orig = b.pipeline.execute.bind(b.pipeline); b.pipeline.execute = async (s: any) => { calls++; return orig(s); }; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b); await s.start('a1', EXCH_BG); await s.run('a1', SIG, P); assert.equal(calls, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });

// 26–34 Restart
test('26. restart running → running', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.restart('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'running'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('27. restart stopped → running', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.restart('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'running'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('28. restart gen increments', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.restart('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).generation, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('29. restart preserves cash', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.run('a1', SIG, P); const cash = b.service.snapshot().cashUsd; await s.restart('a1', EXCH_BG); assert.equal(b.service.snapshot().cashUsd, cash); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('30. restart preserves fills', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.run('a1', SIG, P); await s.restart('a1', EXCH_BG); assert.equal(b.service.snapshot().processedFills, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('31. restart cross-account isolated', async () => { const b1 = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); const b2 = await makeBinding('a2', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b1.binding); s.register(b2.binding); await s.start('a1', EXCH_BG); await s.start('a2', EXCH_BG); await s.run('a1', SIG, P); await s.restart('a1', EXCH_BG); assert.equal(b2.binding.service.snapshot().processedFills, 0); } finally { await fs.rm(b1.dir, { recursive: true, force: true }); await fs.rm(b2.dir, { recursive: true, force: true }); } });
test('32. restart cross-exchange isolated', async () => { const b1 = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); const b2 = await makeBinding('a1', EXCH_BN, 100_000, 'ETHUSDT', 'long'); try { const s = sup(); s.register(b1.binding); s.register(b2.binding); await s.start('a1', EXCH_BG); await s.start('a1', EXCH_BN); await s.run('a1', SIG, P); await s.restart('a1', EXCH_BG); assert.equal(b2.binding.service.snapshot().processedFills, 0); } finally { await fs.rm(b1.dir, { recursive: true, force: true }); await fs.rm(b2.dir, { recursive: true, force: true }); } });
test('33. restart fail → failed', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); ad.startFail = true; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await assert.rejects(() => s.restart('a1', EXCH_BG)); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'failed'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('34. adapter calls on restart from stopped', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await s.restart('a1', EXCH_BG); assert.equal(ad.startCalls, 1); assert.equal(ad.stopCalls, 0); } finally { await fs.rm(d, { recursive: true, force: true }); } });

// 35–42 Unregister
test('35. unregister stopped ok', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); assert.ok(s.unregister('a1', EXCH_BG)); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('36. unregister running rejected', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); assert.throws(() => s.unregister('a1', EXCH_BG), PaperRuntimeLifecycleError); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('37. unregister preserves ledger', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.run('a1', SIG, P); await s.stop('a1', EXCH_BG); s.unregister('a1', EXCH_BG); const svc2 = await PaperExecutionService.open({ accountId: 'a1', exchange: EXCH_BG, initialCashUsd: 100_000 }, new PaperLedgerStore({ accountId: 'a1', exchange: EXCH_BG, initialCashUsd: 100_000 }, { baseDir: d })); assert.equal(svc2.snapshot().processedFills, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });

// 38–42 Batch
test('38. startAll deterministic', async () => { const b1 = await makeBinding('b', EXCH_BG, 100_000, 'BTCUSDT', 'long'); const b2 = await makeBinding('a', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b2.binding); s.register(b1.binding); const res = await s.startAll(); assert.equal(res[0].accountId, 'a'); } finally { await fs.rm(b1.dir, { recursive: true, force: true }); await fs.rm(b2.dir, { recursive: true, force: true }); } });
test('39. stopAll drains', async () => { const b1 = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); const b2 = await makeBinding('a1', EXCH_BN, 100_000, 'ETHUSDT', 'long'); try { const s = sup(); s.register(b1.binding); s.register(b2.binding); await s.startAll(); await s.stopAll(); assert.equal(s.lifecycle('a1', EXCH_BN).state, 'stopped'); } finally { await fs.rm(b1.dir, { recursive: true, force: true }); await fs.rm(b2.dir, { recursive: true, force: true }); } });
test('40. startAll isolates fail', async () => { const b1 = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); const b2 = await makeBinding('a1', EXCH_BN, 100_000, 'ETHUSDT', 'long'); try { const ad = new TrackingAdapter(); ad.startFail = true; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b1.binding, ad); s.register(b2.binding); const res = await s.startAll(); const bns = res.find(r => r.exchange === EXCH_BN)!; assert.equal(bns.success, true); } finally { await fs.rm(b1.dir, { recursive: true, force: true }); await fs.rm(b2.dir, { recursive: true, force: true }); } });

// 43–48 Observability + Misc
test('41. sink fail not break start', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const f = { emit: () => { throw new Error('boom'); } }; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry(), eventSink: f }); s.register(b); await s.start('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'running'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('42. sink fail not break stop', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const f = { emit: () => { throw new Error('boom'); } }; const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry(), eventSink: f }); s.register(b); await s.start('a1', EXCH_BG); await s.stop('a1', EXCH_BG); assert.equal(s.lifecycle('a1', EXCH_BG).state, 'stopped'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('43. registry unchanged', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.run('a1', SIG, P); await s.run('a1', SIG, P); assert.equal(b.service.snapshot().processedFills, 2); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('44. zero live exec', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); assert.ok(await s.run('a1', SIG, P)); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('45. start during restart rejected', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); const rp = s.restart('a1', EXCH_BG); const sp = s.start('a1', EXCH_BG); const [rr, sr] = await Promise.allSettled([rp, sp]); assert.ok(rr.status === 'fulfilled' || sr.status === 'rejected'); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('46. multi fills through lifecycle', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const s = sup(); s.register(b); await s.start('a1', EXCH_BG); await s.run('a1', SIG, P); await s.run('a1', SIG, P); assert.equal(b.service.snapshot().processedFills, 2); } finally { await fs.rm(d, { recursive: true, force: true }); } });
test('47. lifecycleAll empty', () => { assert.equal(sup().lifecycleAll().length, 0); });
test('48. bound adapter not shared', async () => { const { binding: b, dir: d } = await makeBinding('a1', EXCH_BG, 100_000, 'BTCUSDT', 'long'); try { const ad = new TrackingAdapter(); const s = new PaperRuntimeSupervisor({ registry: new PaperRuntimeRegistry() }); s.register(b, ad); await s.start('a1', EXCH_BG); assert.equal(ad.startCalls, 1); } finally { await fs.rm(d, { recursive: true, force: true }); } });
